export const EXTENDED_POSES_4 = {
    // ==================== ADVANCED BALANCES ====================
    standing_hand_to_big_toe: { name: 'Standing Hand to Big Toe', sanskrit: 'Utthita Hasta Padangusthasana', category: 'balancing', level: 'advanced', duration: { min: 15, max: 45 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'flexibility'], bodyParts: ['hamstrings', 'hips', 'core'], contraindications: ['ankle injury'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['tree_pose'] }, narrationHints: { energetic: 'Grab your big toe with peace fingers. Kick your heel forward and stand tall!' } },
    flamingo_pose: { name: 'Flamingo Pose', sanskrit: 'Utthita Stiti Surya Yantrasana', category: 'balancing', level: 'intermediate', duration: { min: 15, max: 30 }, audiences: ['adults', 'intermediate', 'kids'], focusAreas: ['balance'], bodyParts: ['legs', 'core'], contraindications: ['knee injury'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['dancer_pose'] }, narrationHints: { kids: 'Bend one leg behind you like a beautiful pink flamingo standing in the water.' } },
    figure_four_chair: { name: 'Figure Four Chair', sanskrit: 'Eka Pada Utkatasana', category: 'balancing', level: 'intermediate', duration: { min: 20, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['balance', 'hip-opener'], bodyParts: ['hips', 'glutes', 'core'], contraindications: ['knee injury'], transitions: { goodBefore: ['chair_pose'], goodAfter: ['standing_forward_fold'] }, narrationHints: { energetic: 'Cross ankle over opposite knee and sit deep into that one-legged chair.' } },
    flying_pigeon: { name: 'Flying Pigeon', sanskrit: 'Eka Pada Galavasana', category: 'balancing', level: 'advanced', duration: { min: 10, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'strength', 'core'], bodyParts: ['arms', 'core', 'hips'], contraindications: ['wrist injury', 'hip injury'], transitions: { goodBefore: ['figure_four_chair'], goodAfter: ['chaturanga'] }, narrationHints: { energetic: 'Hook the toes around your tricep, lean forward, and take the back leg to the sky!' } },
    side_crow: { name: 'Side Crow', sanskrit: 'Parsva Bakasana', category: 'balancing', level: 'advanced', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'strength', 'twists'], bodyParts: ['arms', 'obliques'], contraindications: ['wrist injury'], transitions: { goodBefore: ['revolved_chair'], goodAfter: ['plank_pose'] }, narrationHints: { energetic: 'Twist deeply, plant your hands, and float both legs off to the side.' } },
    eight_angle_pose: { name: 'Eight Angle Pose', sanskrit: 'Astavakrasana', category: 'balancing', level: 'advanced', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['strength', 'core'], bodyParts: ['arms', 'core'], contraindications: ['wrist injury', 'shoulder injury'], transitions: { goodBefore: ['boat_pose'], goodAfter: ['chaturanga'] }, narrationHints: { energetic: 'Hook your leg over your shoulder, cross your ankles, and squeeze your arm to lift off.' } },
    firefly_pose: { name: 'Firefly Pose', sanskrit: 'Tittibhasana', category: 'balancing', level: 'advanced', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'core', 'flexibility'], bodyParts: ['arms', 'core', 'hamstrings'], contraindications: ['wrist injury'], transitions: { goodBefore: ['wide_legged_forward_fold'], goodAfter: ['crow_pose'] }, narrationHints: { energetic: 'Squeeze the triceps with your inner thighs, straighten your legs, and fly!' } },
    scale_pose: { name: 'Scale Pose', sanskrit: 'Tolasana', category: 'balancing', level: 'advanced', duration: { min: 10, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['core', 'strength'], bodyParts: ['core', 'arms'], contraindications: ['wrist injury'], transitions: { goodBefore: ['lotus_pose'], goodAfter: ['easy_pose'] }, narrationHints: { energetic: 'Plant your hands beside your hips and lift your entire Lotus off the floor.' } },
    l_sit: { name: 'L-Sit', sanskrit: 'Brahmacharyasana', category: 'floor', level: 'advanced', duration: { min: 5, max: 15 }, audiences: ['adults', 'advanced', 'athletes'], focusAreas: ['core', 'strength'], bodyParts: ['core', 'arms', 'hip-flexors'], contraindications: ['wrist injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['boat_pose'] }, narrationHints: { energetic: 'Press down into your palms and lift your hips and heels off the ground, forming a perfect L.' } },
    fallen_triangle: { name: 'Fallen Triangle', sanskrit: 'Patita Tarasana', category: 'floor', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate'], focusAreas: ['strength', 'energy'], bodyParts: ['chest', 'core', 'arms'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['three_legged_dog'], goodAfter: ['downward_facing_dog'] }, narrationHints: { energetic: 'Thread your leg underneath, drop the outer foot, and open your heart to the ceiling!' } },
    
    // ==================== ADVANCED CORE ====================
    low_boat_pose: { name: 'Low Boat Pose', sanskrit: 'Ardha Navasana', category: 'floor', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate'], focusAreas: ['core'], bodyParts: ['core', 'lower-back'], contraindications: ['lower back injury'], transitions: { goodBefore: ['boat_pose'], goodAfter: ['savasana'] }, narrationHints: { energetic: 'Hover your shoulders and heels just one inch off the mat. Hold it, shake with it!' } },
    core_plank_knee_to_nose: { name: 'Plank Knee to Nose', sanskrit: 'Phalakasana Knee to Nose', category: 'floor', level: 'intermediate', duration: { min: 10, max: 30 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['core', 'strength'], bodyParts: ['core', 'shoulders'], contraindications: ['wrist injury'], transitions: { goodBefore: ['three_legged_dog'], goodAfter: ['low_lunge'] }, narrationHints: { energetic: 'Shift forward, round your upper back like a cat, and kiss your knee!' } },
    side_plank_tree: { name: 'Side Plank Tree', sanskrit: 'Vasisthasana Tree Legs', category: 'floor', level: 'intermediate', duration: { min: 15, max: 30 }, audiences: ['adults', 'intermediate'], focusAreas: ['balance', 'strength'], bodyParts: ['obliques', 'arms'], contraindications: ['wrist injury'], transitions: { goodBefore: ['side_plank'], goodAfter: ['plank_pose'] }, narrationHints: { energetic: 'Bring your top foot to your inner thigh. Hips high, steady balance.' } },
    star_plank: { name: 'Star Plank', sanskrit: 'Utthita Vasisthasana', category: 'floor', level: 'advanced', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'strength'], bodyParts: ['obliques', 'arms', 'outer-thighs'], contraindications: ['wrist injury'], transitions: { goodBefore: ['side_plank'], goodAfter: ['chaturanga'] }, narrationHints: { energetic: 'Hover that top leg high toward the sky, form a five-pointed star of strength.' } },
    forearm_side_plank: { name: 'Forearm Side Plank', sanskrit: 'Makara Vasisthasana', category: 'floor', level: 'intermediate', duration: { min: 20, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['core', 'strength'], bodyParts: ['obliques', 'shoulders'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['forearm_plank'], goodAfter: ['sphinx_pose'] }, narrationHints: { energetic: 'Roll to the outer edge of your foot and reach the top arm up. Keep the shoulder stable.' } },

    // ==================== KNEELING & SHIN BALANCES ====================
    gate_pose: { name: 'Gate Pose', sanskrit: 'Parighasana', category: 'floor', level: 'beginner', duration: { min: 20, max: 60 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'breathing'], bodyParts: ['side-body', 'obliques'], contraindications: ['knee injury'], transitions: { goodBefore: ['cat_cow'], goodAfter: ['childs_pose'] }, narrationHints: { beginner: 'Kneel, extend one leg out, and slide your hand down your leg for a deep side stretch.' } },
    tiger_pose: { name: 'Tiger Pose', sanskrit: 'Vyaghrasana', category: 'floor', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['adults', 'beginners'], focusAreas: ['back-pain', 'flexibility'], bodyParts: ['spine', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['cat_cow'], goodAfter: ['childs_pose'] }, narrationHints: { beginner: 'Lift one leg high behind you, bend the knee, and look up to arch your back.' } },
    bird_dog: { name: 'Bird Dog', sanskrit: 'Dandayamana Bharmanasana', category: 'floor', level: 'beginner', duration: { min: 15, max: 45 }, audiences: ['adults', 'beginners', 'athletes'], focusAreas: ['core', 'balance'], bodyParts: ['core', 'glutes', 'shoulders'], contraindications: [], transitions: { goodBefore: ['cat_cow'], goodAfter: ['plank_pose'] }, narrationHints: { beginner: 'Extend opposite arm and leg. Pull your belly button to your spine to stabilize.' } },
    balancing_table: { name: 'Balancing Table Twist', sanskrit: 'Parivrtta Bharmanasana', category: 'floor', level: 'intermediate', duration: { min: 15, max: 30 }, audiences: ['adults', 'intermediate'], focusAreas: ['balance', 'flexibility'], bodyParts: ['core', 'spine'], contraindications: ['knee injury'], transitions: { goodBefore: ['bird_dog'], goodAfter: ['tiger_pose'] }, narrationHints: { energetic: 'Reach back with your extended hand to grab your lifted foot and kick into your hand.' } },
    kneeling_lunge: { name: 'Kneeling Lunge', sanskrit: 'Ashwa Sanchalanasana', category: 'floor', level: 'beginner', duration: { min: 20, max: 60 }, audiences: ['adults', 'beginners'], focusAreas: ['flexibility', 'hip-opener'], bodyParts: ['hip-flexors', 'quads'], contraindications: ['knee injury'], transitions: { goodBefore: ['downward_facing_dog'], goodAfter: ['half_splits'] }, narrationHints: { beginner: 'Drop your back knee, untuck your toes, and let your hips sink heavy toward the top heel.' } }
};
