export const EXTENDED_POSES_6 = {
    // ==================== DEEP BACKBENDS ====================
    camel_pose: { name: 'Camel Pose', sanskrit: 'Ustrasana', category: 'backbend', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility', 'energy'], bodyParts: ['chest', 'shoulders', 'spine'], contraindications: ['lower back injury', 'neck injury'], transitions: { goodBefore: ['heros_pose'], goodAfter: ['childs_pose'] }, narrationHints: { energetic: 'Kneel upright, sweep your hands back to your heels, and lift your sternum to the sky.' } },
    wheel_pose: { name: 'Wheel Pose', sanskrit: 'Urdhva Dhanurasana', category: 'backbend', level: 'advanced', duration: { min: 10, max: 30 }, audiences: ['adults', 'advanced', 'athletes'], focusAreas: ['strength', 'flexibility', 'energy'], bodyParts: ['spine', 'arms', 'shoulders', 'chest'], contraindications: ['wrist injury', 'back injury', 'high blood pressure'], transitions: { goodBefore: ['bridge_pose'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { energetic: 'Press into hands and feet, straighten the arms, and push your chest through your shoulders!' } },
    bridge_pose: { name: 'Bridge Pose', sanskrit: 'Setu Bandhasana', category: 'backbend', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['adults', 'beginners', 'seniors'], focusAreas: ['back-pain', 'strength'], bodyParts: ['glutes', 'spine', 'chest'], contraindications: ['neck injury'], transitions: { goodBefore: ['savasana'], goodAfter: ['wheel_pose', 'wind_relieving_pose'] }, narrationHints: { beginner: 'Press into your heels and lift your hips high. Shimmy your shoulders under.' } },
    one_legged_bridge: { name: 'One-Legged Bridge', sanskrit: 'Eka Pada Setu Bandhasana', category: 'backbend', level: 'intermediate', duration: { min: 15, max: 30 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['strength', 'core'], bodyParts: ['glutes', 'core'], contraindications: ['neck injury'], transitions: { goodBefore: ['bridge_pose'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { energetic: 'Keep hips level as you extend one leg straight up to the ceiling, stamping the sky.' } },
    pigeon_pose: { name: 'Pigeon Pose', sanskrit: 'Eka Pada Rajakapotasana (Prep)', category: 'hip_opener', level: 'intermediate', duration: { min: 60, max: 180 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['flexibility', 'emotion-release'], bodyParts: ['hips', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['downward_facing_dog'], goodAfter: ['downward_facing_dog'] }, narrationHints: { relaxation: 'Walk your hands forward and sleep your pigeon. Let the earth support your heavy hips.' } },
    
    // ==================== ADVANCED HEART OPENERS ====================
    upward_facing_two_foot_staff: { name: 'Upward Two-Foot Staff', sanskrit: 'Dwi Pada Viparita Dandasana', category: 'backbend', level: 'advanced', duration: { min: 10, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'energy'], bodyParts: ['shoulders', 'spine', 'chest'], contraindications: ['neck injury', 'back injury'], transitions: { goodBefore: ['wheel_pose'], goodAfter: ['childs_pose'] }, narrationHints: { energetic: 'From wheel, drop to your forearms, interlace fingers behind the head, and open the chest completely.' } },
    king_arthur_pose: { name: 'King Arthur Pose', sanskrit: 'King Arthur', category: 'hip_opener', level: 'advanced', duration: { min: 30, max: 60 }, audiences: ['adults', 'advanced', 'athletes'], focusAreas: ['flexibility'], bodyParts: ['quads', 'hip-flexors'], contraindications: ['knee injury'], transitions: { goodBefore: ['low_lunge'], goodAfter: ['half_splits'] }, narrationHints: { energetic: 'Take your back shin up the wall, sink your hips, and feel the massive opening in the quad.' } },
    mermaid_pose: { name: 'Mermaid Pose', sanskrit: 'Eka Pada Rajakapotasana Variation', category: 'backbend', level: 'advanced', duration: { min: 15, max: 45 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'balance'], bodyParts: ['quads', 'shoulders', 'spine'], contraindications: ['knee injury', 'shoulder injury'], transitions: { goodBefore: ['pigeon_pose'], goodAfter: ['downward_facing_dog'] }, narrationHints: { poetic: 'Hook your back foot into the elbow crease, clasp hands behind the head, and lift your chest like a mermaid breaching water.' } },
    full_camel: { name: 'Full Camel (Kapotasana)', sanskrit: 'Kapotasana', category: 'backbend', level: 'master', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'energy'], bodyParts: ['spine', 'shoulders', 'chest'], contraindications: ['back injury', 'neck injury'], transitions: { goodBefore: ['camel_pose'], goodAfter: ['childs_pose'] }, narrationHints: { energetic: 'Walk your hands down the wall or back to your feet, forearms to the floor for the deepest heart opener.' } },
    scorpion_pose: { name: 'Scorpion Pose', sanskrit: 'Vrschikasana', category: 'inversion', level: 'master', duration: { min: 10, max: 20 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'flexibility'], bodyParts: ['spine', 'arms', 'core'], contraindications: ['neck injury', 'back injury'], transitions: { goodBefore: ['forearm_stand'], goodAfter: ['childs_pose'] }, narrationHints: { energetic: 'Drop your chest, bend the knees, and bring your toes toward the crown of your head like a scorpion stinger.' } },

    // ==================== BINDING & STANDING BACKBENDS ====================
    standing_split: { name: 'Standing Split', sanskrit: 'Urdhva Prasarita Eka Padasana', category: 'standing', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['flexibility', 'balance'], bodyParts: ['hamstrings', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['standing_forward_fold'], goodAfter: ['low_lunge'] }, narrationHints: { energetic: 'Forehead to shin, lift the back leg as high as you can to the ceiling!' } },
    dancer_pose_c: { name: 'King Dancer', sanskrit: 'Natarajasana (Full Bind)', category: 'balancing', level: 'advanced', duration: { min: 15, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'balance', 'energy'], bodyParts: ['spine', 'shoulders'], contraindications: ['back injury', 'shoulder injury'], transitions: { goodBefore: ['dancer_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { poetic: 'Flip the grip over your head, grab the foot with both hands, and kick back into the beautiful cosmic dance line.' } },
    lord_of_the_dance: { name: 'Lord of the Dance', sanskrit: 'Natarajasana', category: 'balancing', level: 'intermediate', duration: { min: 20, max: 45 }, audiences: ['adults', 'intermediate'], focusAreas: ['balance', 'flexibility'], bodyParts: ['quads', 'spine', 'chest'], contraindications: ['knee injury'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['standing_forward_fold'] }, narrationHints: { beginner: 'Kick your back foot into your hand to lift the chest. Reach the front arm forward to balance.' } },
    sugar_cane_pose: { name: 'Sugar Cane Pose', sanskrit: 'Chapasana', category: 'balancing', level: 'advanced', duration: { min: 15, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'flexibility'], bodyParts: ['quads', 'core'], contraindications: ['knee injury'], transitions: { goodBefore: ['half_moon'], goodAfter: ['warrior_2'] }, narrationHints: { energetic: 'From half moon, bend the top knee, grab the foot, and kick back to open the front side of the body.' } },
    balancing_stick: { name: 'Balancing Stick', sanskrit: 'Tuladandasana', category: 'balancing', level: 'intermediate', duration: { min: 10, max: 20 }, audiences: ['adults', 'athletes'], focusAreas: ['strength', 'energy'], bodyParts: ['core', 'shoulders', 'legs'], contraindications: ['high blood pressure'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { energetic: 'Interlace fingers, step forward, and bring body parallel to the floor. Pull yourself apart in two directions!' } },

    // ==================== MORE SEATED BACKBENDS ====================
    upward_plank: { name: 'Upward Plank', sanskrit: 'Purvottanasana', category: 'seated', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['strength', 'flexibility'], bodyParts: ['shoulders', 'wrists', 'core'], contraindications: ['wrist injury', 'neck injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['seated_forward_fold'] }, narrationHints: { energetic: 'Point toes, lift hips, and open the entire front line of the body. Keep the neck long.' } },
    reverse_tabletop: { name: 'Reverse Tabletop', sanskrit: 'Ardha Purvottanasana', category: 'floor', level: 'beginner', duration: { min: 20, max: 60 }, audiences: ['adults', 'beginners'], focusAreas: ['strength', 'flexibility'], bodyParts: ['shoulders', 'glutes'], contraindications: ['wrist injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['seated_forward_fold'] }, narrationHints: { beginner: 'Bend knees, plant feet, and lift hips up to make a flat table with your body.' } },
    supported_bridge: { name: 'Supported Bridge', sanskrit: 'Salamba Setu Bandhasana', category: 'restorative', level: 'beginner', duration: { min: 60, max: 300 }, audiences: ['adults', 'beginners', 'pregnant', 'seniors'], focusAreas: ['relaxation', 'back-pain'], bodyParts: ['spine', 'lower-back'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { relaxation: 'Slide a block under your sacrum and rest all your weight onto it. Soothing for the lower back.' } },
    wild_thing_seated: { name: 'Seated Wild Thing', sanskrit: 'Seated Camatkarasana', category: 'seated', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['adults', 'beginners'], focusAreas: ['flexibility', 'energy'], bodyParts: ['chest', 'hips'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['head_to_knee'], goodAfter: ['staff_pose'] }, narrationHints: { energetic: 'Plant the hand behind you, lift the hips, and reach the arm back for a glorious stretch.' } },
    half_frog_pose: { name: 'Half Frog Pose', sanskrit: 'Ardha Bhekasana', category: 'floor', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'intermediate', 'athletes'], focusAreas: ['flexibility'], bodyParts: ['quads', 'chest'], contraindications: ['knee injury'], transitions: { goodBefore: ['sphinx_pose'], goodAfter: ['childs_pose'] }, narrationHints: { energetic: 'From sphinx, bend one knee, reach back, and press the foot down alongside your hip.' } }
};
