export const EXTENDED_POSES_8 = {
    // ==================== FUN ANIMAL & NATURE POSES (KIDS FOCUS) ====================
    bear_walk: { name: 'Bear Walk', sanskrit: 'Bear Walk', category: 'floor', level: 'beginner', duration: { min: 20, max: 45 }, audiences: ['kids', 'beginners'], focusAreas: ['energy', 'strength'], bodyParts: ['arms', 'legs', 'core'], contraindications: [], transitions: { goodBefore: ['downward_facing_dog'], goodAfter: ['standing_forward_fold'] }, narrationHints: { kids: 'Walk on your hands and feet without bending your knees too much, just like a big fluffy bear searching for honey!' } },
    crab_pose: { name: 'Crab Pose', sanskrit: 'Reverse Tabletop Variation', category: 'floor', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['kids', 'beginners'], focusAreas: ['strength', 'balance'], bodyParts: ['arms', 'core'], contraindications: ['wrist injury'], transitions: { goodBefore: ['seated_forward_fold'], goodAfter: ['boat_pose'] }, narrationHints: { kids: 'Lift your belly up flat like a table, then try to walk sideways like a crab on the beach! Snap snap!' } },
    kangaroo_hops: { name: 'Kangaroo Hops', sanskrit: 'Kangaroo Hops', category: 'standing', level: 'beginner', duration: { min: 10, max: 30 }, audiences: ['kids'], focusAreas: ['energy', 'strength'], bodyParts: ['legs', 'heart'], contraindications: ['knee injury'], transitions: { goodBefore: ['chair_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { kids: 'Tuck your hands by your chest like a kangaroo pouch and hop up high!' } },
    snake_pose: { name: 'Snake Pose', sanskrit: 'Sarpasana', category: 'backbend', level: 'beginner', duration: { min: 10, max: 20 }, audiences: ['kids', 'beginners'], focusAreas: ['flexibility', 'strength'], bodyParts: ['spine', 'chest'], contraindications: ['back injury'], transitions: { goodBefore: ['cobra_pose'], goodAfter: ['childs_pose'] }, narrationHints: { kids: 'Lock hands behind your back, lift your chest and hiss loudly like a long sneaky snake! Ssssss!' } },
    turtle_pose: { name: 'Turtle Pose', sanskrit: 'Kurmasana Variation', category: 'seated', level: 'beginner', duration: { min: 20, max: 45 }, audiences: ['kids', 'beginners'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['spine', 'hips'], contraindications: ['back injury'], transitions: { goodBefore: ['butterfly_pose'], goodAfter: ['easy_pose'] }, narrationHints: { kids: 'Slide your arms under your knees and hide your head in your shell to feel safe and quiet.' } },

    // ==================== MORE KIDS BALANCES ====================
    stork_pose: { name: 'Stork Pose', sanskrit: 'One Legged Balance', category: 'balancing', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['kids', 'beginners'], focusAreas: ['balance'], bodyParts: ['legs', 'core'], contraindications: ['balance disorders'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['tree_pose'] }, narrationHints: { kids: 'Stand extra tall on one leg, tuck your hands like wings. Look out for fish in the pond!' } },
    star_pose: { name: 'Star Pose', sanskrit: 'Utthita Tadasana', category: 'standing', level: 'beginner', duration: { min: 10, max: 20 }, audiences: ['kids', 'beginners'], focusAreas: ['energy', 'posture'], bodyParts: ['full-body'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['goddess_pose'] }, narrationHints: { kids: 'Step wide, stretch arms wide, spread your fingers! You are a brilliant shining star in the sky!' } },
    crescent_moon_pose: { name: 'Crescent Moon Pose', sanskrit: 'Indudalasana', category: 'standing', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['kids', 'beginners', 'adults'], focusAreas: ['flexibility'], bodyParts: ['side-body'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['standing_forward_fold'] }, narrationHints: { kids: 'Reach up high, glue hands together, and lean to the side like a glowing crescent moon.' } },
    washing_machine: { name: 'Washing Machine Twist', sanskrit: 'Standing Twists', category: 'standing', level: 'beginner', duration: { min: 20, max: 45 }, audiences: ['kids', 'beginners', 'office-workers'], focusAreas: ['energy', 'stress-relief'], bodyParts: ['spine', 'arms'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { kids: 'Swish side to side like a washing machine! Let your arms flop and clean out all the messy thoughts!' } },
    bumpy_camel: { name: 'Bumpy Camel', sanskrit: 'Camel Variation', category: 'backbend', level: 'beginner', duration: { min: 10, max: 20 }, audiences: ['kids'], focusAreas: ['flexibility'], bodyParts: ['chest', 'spine'], contraindications: ['back injury'], transitions: { goodBefore: ['heros_pose'], goodAfter: ['childs_pose'] }, narrationHints: { kids: 'Put your hands on your lower back to make camel humps, then look up to the hot desert sun!' } },

    // ==================== PRENATAL & GENTLE MODIFICATIONS ====================
    cat_cow_seated: { name: 'Seated Cat Cow', sanskrit: 'Seated Marjaryasana', category: 'warmup', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['adults', 'pregnant', 'seniors', 'office-workers'], focusAreas: ['back-pain', 'flexibility'], bodyParts: ['spine', 'chest'], contraindications: [], transitions: { goodBefore: ['easy_pose'], goodAfter: ['seated_side_bend'] }, narrationHints: { beginner: 'Hands on knees, inhale pull chest forward, exhale round the back backward. Great when wrists are tired.' } },
    goddess_squat_wall: { name: 'Supported Goddess (Wall)', sanskrit: 'Wall Utkata Konasana', category: 'standing', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['pregnant', 'beginners', 'seniors'], focusAreas: ['strength'], bodyParts: ['quads', 'hips'], contraindications: ['knee injury'], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { beginner: 'Lean your back flat against the wall and slide down into a safe squat to build leg strength safely.' } },
    puppy_pose_wall: { name: 'Wall Puppy Dog', sanskrit: 'Wall Down Dog', category: 'standing', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['pregnant', 'beginners', 'seniors'], focusAreas: ['flexibility', 'posture'], bodyParts: ['shoulders', 'spine'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { beginner: 'A great prenatal alternative to down dog. Hands to the wall, walk feet back, melt chest.' } },
    modified_side_plank: { name: 'Modified Side Plank', sanskrit: 'Modified Vasisthasana', category: 'floor', level: 'beginner', duration: { min: 15, max: 45 }, audiences: ['pregnant', 'beginners'], focusAreas: ['strength', 'core'], bodyParts: ['obliques', 'arms'], contraindications: ['wrist injury'], transitions: { goodBefore: ['cat_cow'], goodAfter: ['plank_pose'] }, narrationHints: { beginner: 'Drop bottom knee to the floor for support, keeping the top leg straight and top arm high.' } },
    side_lying_savasana: { name: 'Side-Lying Savasana', sanskrit: 'Parsva Savasana', category: 'restorative', level: 'beginner', duration: { min: 180, max: 600 }, audiences: ['pregnant', 'adults', 'beginners'], focusAreas: ['relaxation', 'sleep'], bodyParts: ['nervous-system'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['easy_pose'] }, narrationHints: { relaxation: 'Roll to your left side, place a pillow between your knees and under your head for ultimate safety and rest.' } },

    // ==================== OFFICE DESK POSES ====================
    desk_chaturanga: { name: 'Desk Chaturanga', sanskrit: 'Desk Plank', category: 'standing', level: 'beginner', duration: { min: 15, max: 30 }, audiences: ['office-workers', 'beginners'], focusAreas: ['strength', 'energy'], bodyParts: ['chest', 'triceps'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { beginner: 'Hands on sturdy desk, step back, and do a slow controlled push-up against the desk edge.' } },
    seated_pigeon_chair: { name: 'Chair Pigeon', sanskrit: 'Seated Figure Four', category: 'seated', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['office-workers', 'seniors', 'beginners'], focusAreas: ['flexibility', 'hip-opener'], bodyParts: ['glutes', 'hips'], contraindications: ['knee injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['easy_pose'] }, narrationHints: { beginner: 'Sitting in your chair, cross right ankle over left knee. Lean forward gently with a flat back.' } },
    desk_shoulder_opener: { name: 'Desk Shoulder Opener', sanskrit: 'Desk Puppy', category: 'standing', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['office-workers', 'beginners'], focusAreas: ['posture', 'back-pain'], bodyParts: ['shoulders', 'chest'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { beginner: 'Stand back from desk, hands on edge, drop head between arms. Reverse the computer hump!' } },
    wrist_stretches: { name: 'Wrist Stretches', sanskrit: 'Wrist Relief', category: 'warmup', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['office-workers', 'adults', 'athletes'], focusAreas: ['flexibility'], bodyParts: ['wrists', 'forearms'], contraindications: ['severe carpal tunnel'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['cat_cow'] }, narrationHints: { beginner: 'Extend arm, gently pull fingers down with other hand. Switch and pull fingers up.' } },
    neck_rolls: { name: 'Neck Rolls', sanskrit: 'Greeva Sanchalana', category: 'warmup', level: 'beginner', duration: { min: 30, max: 60 }, audiences: ['office-workers', 'all', 'kids', 'seniors'], focusAreas: ['stress-relief', 'relaxation'], bodyParts: ['neck', 'upper-back'], contraindications: ['whiplash'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['shoulder_rolls'] }, narrationHints: { relaxation: 'Drop chin to chest, roll ear to shoulder, forming slow half circles to crack away the tension.' } }
};
