export const EXTENDED_POSES_5 = {
    // ==================== ASHTANGA SEATED & TWISTS ====================
    marichyasana_a: { name: 'Marichi Pose A', sanskrit: 'Marichyasana A', category: 'seated', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility'], bodyParts: ['shoulders', 'hamstrings'], contraindications: ['knee injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['marichyasana_c'] }, narrationHints: { beginner: 'Bend one knee, reach the same arm forward and wrap it around the shin to bind behind your back.' } },
    marichyasana_c: { name: 'Marichi Pose C (Twist)', sanskrit: 'Marichyasana C', category: 'twist', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['digestion', 'twists'], bodyParts: ['spine', 'shoulders'], contraindications: ['back injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['seated_forward_fold'] }, narrationHints: { beginner: 'Hug your bent knee or hook the elbow outside of it, twisting deeply over your shoulder.' } },
    half_bound_lotus_forward_fold: { name: 'Half Bound Lotus Forward Fold', sanskrit: 'Ardha Baddha Padma Paschimottanasana', category: 'seated', level: 'advanced', duration: { min: 30, max: 60 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility'], bodyParts: ['knees', 'hips', 'hamstrings'], contraindications: ['knee injury', 'hip injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['head_to_knee'] }, narrationHints: { beginner: 'Place one foot into half lotus, reach behind to bind the big toe, and fold forward.' } },
    triang_mukha_ekapada: { name: 'Triang Mukha Ekapada Paschimottanasana', sanskrit: 'Trianga Mukhaikapada Paschimottanasana', category: 'seated', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility'], bodyParts: ['quads', 'hamstrings'], contraindications: ['knee injury'], transitions: { goodBefore: ['heros_pose'], goodAfter: ['staff_pose'] }, narrationHints: { beginner: 'Fold one leg back like hero pose, keep the other straight, and fold forward.' } },
    sewing_machine: { name: 'Sewing Machine (Janu Sirsasana B)', sanskrit: 'Janu Sirsasana B', category: 'seated', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility'], bodyParts: ['hips', 'hamstrings'], contraindications: ['knee injury'], transitions: { goodBefore: ['head_to_knee'], goodAfter: ['staff_pose'] }, narrationHints: { beginner: 'Sit on your heel of the bent leg and fold over the straight leg.' } },
    
    // ==================== LOTUS & MEDITATION ====================
    lotus_pose: { name: 'Lotus Pose', sanskrit: 'Padmasana', category: 'seated', level: 'advanced', duration: { min: 60, max: 300 }, audiences: ['adults', 'advanced'], focusAreas: ['meditation', 'relaxation'], bodyParts: ['hips', 'knees', 'ankles'], contraindications: ['knee injury', 'ankle injury'], transitions: { goodBefore: ['butterfly_pose'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Carefully cross both feet onto opposite thighs. Sit perfectly still, spine aligned like a stacked coins.' } },
    half_lotus: { name: 'Half Lotus', sanskrit: 'Ardha Padmasana', category: 'seated', level: 'intermediate', duration: { min: 60, max: 300 }, audiences: ['adults', 'intermediate'], focusAreas: ['meditation', 'relaxation'], bodyParts: ['hips', 'knees'], contraindications: ['knee injury'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['lotus_pose'] }, narrationHints: { relaxation: 'Bring one foot on top of the opposite thigh. Find a comfortable, grounded seat for your breath.' } },
    accomplished_pose: { name: 'Accomplished Pose', sanskrit: 'Siddhasana', category: 'seated', level: 'beginner', duration: { min: 60, max: 300 }, audiences: ['adults', 'beginners', 'seniors'], focusAreas: ['meditation', 'posture'], bodyParts: ['hips', 'spine'], contraindications: ['knee injury'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Line up your heels in front of your pelvis. A perfect seat for focusing the mind.' } },
    bound_angle_forward_fold: { name: 'Bound Angle Forward Fold', sanskrit: 'Baddha Konasana A', category: 'seated', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['inner-thighs', 'spine'], contraindications: ['lower back injury'], transitions: { goodBefore: ['butterfly_pose'], goodAfter: ['staff_pose'] }, narrationHints: { relaxation: 'Round your spine gently over your butterfly legs. Let the head hang heavy.' } },
    shooting_bow: { name: 'Shooting Bow', sanskrit: 'Akarna Dhanurasana', category: 'seated', level: 'advanced', duration: { min: 15, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'core'], bodyParts: ['hips', 'arms'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['seated_forward_fold'], goodAfter: ['boat_pose'] }, narrationHints: { energetic: 'Grab your big toes, pull one foot back to your ear like drawing a bowstring. Aim true!' } },

    // ==================== ABDOMINAL TWISTS ====================
    jathara_parivartanasana: { name: 'Revolved Abdomen Pose', sanskrit: 'Jathara Parivartanasana', category: 'supine', level: 'intermediate', duration: { min: 30, max: 90 }, audiences: ['adults', 'intermediate'], focusAreas: ['core', 'twists'], bodyParts: ['core', 'spine'], contraindications: ['back injury'], transitions: { goodBefore: ['savasana'], goodAfter: ['happy_baby'] }, narrationHints: { energetic: 'Hover your straight legs at a 45 degree angle, then twist them over to the right without dropping them.' } },
    wind_relieving_pose: { name: 'Wind Relieving Pose', sanskrit: 'Pawanmuktasana', category: 'supine', level: 'beginner', duration: { min: 30, max: 120 }, audiences: ['adults', 'kids', 'beginners', 'seniors'], focusAreas: ['digestion', 'relaxation'], bodyParts: ['hips', 'lower-back'], contraindications: ['recent abdominal surgery'], transitions: { goodBefore: ['savasana'], goodAfter: ['reclined_twist'] }, narrationHints: { beginner: 'Hug your right knee tight into your chest, compressing the belly. Deep breaths.' } },
    supine_core_drops: { name: 'Leg Drops', sanskrit: 'Urdhva Prasarita Padasana', category: 'supine', level: 'intermediate', duration: { min: 30, max: 60 }, audiences: ['adults', 'athletes'], focusAreas: ['core', 'energy'], bodyParts: ['lower-core', 'hip-flexors'], contraindications: ['lower back pain'], transitions: { goodBefore: ['savasana'], goodAfter: ['happy_baby'] }, narrationHints: { energetic: 'Lower both straight legs down to a hover, then pull them back up using just your lower abs.' } },
    supine_hand_to_toe: { name: 'Reclined Hand to Big Toe', sanskrit: 'Supta Padangusthasana', category: 'supine', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['adults', 'beginners', 'athletes'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['hamstrings', 'hips'], contraindications: ['hamstring injury'], transitions: { goodBefore: ['savasana'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { relaxation: 'Use a strap or your peace fingers to extend one leg up to the sky, keeping the lower back glued down.' } },
    supine_hand_to_toe_side: { name: 'Reclined Leg to Side', sanskrit: 'Supta Padangusthasana B', category: 'supine', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['adults', 'beginners', 'athletes'], focusAreas: ['flexibility', 'hip-opener'], bodyParts: ['inner-thighs', 'hips'], contraindications: ['groin injury'], transitions: { goodBefore: ['supine_hand_to_toe'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { relaxation: 'Open your extended leg out to the side. Keep both hip bones anchored to the mat.' } },

    // ==================== KNOTS & BINDS ====================
    noose_pose: { name: 'Noose Pose', sanskrit: 'Pasasana', category: 'twist', level: 'advanced', duration: { min: 15, max: 30 }, audiences: ['adults', 'advanced'], focusAreas: ['twists', 'balance'], bodyParts: ['ankles', 'spine', 'shoulders'], contraindications: ['knee injury', 'back injury'], transitions: { goodBefore: ['chair_pose'], goodAfter: ['garland_pose'] }, narrationHints: { energetic: 'Squat down, twist your torso around your thighs, and bind your arms behind your back.' } },
    bound_extended_side_angle: { name: 'Bound Side Angle', sanskrit: 'Baddha Parsvakonasana', category: 'standing', level: 'intermediate', duration: { min: 15, max: 45 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility', 'strength'], bodyParts: ['shoulders', 'hips', 'legs'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['extended_side_angle'], goodAfter: ['bird_of_paradise'] }, narrationHints: { energetic: 'Wrap the top arm behind the back, reach the bottom arm under the thigh, and clasp hands.' } },
    bird_of_paradise_prep: { name: 'Bird of Paradise Prep', sanskrit: 'Baddha Utthita Parsvakonasana Prep', category: 'standing', level: 'intermediate', duration: { min: 15, max: 30 }, audiences: ['adults', 'intermediate'], focusAreas: ['balance', 'strength'], bodyParts: ['legs'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['bound_extended_side_angle'], goodAfter: ['bird_of_paradise'] }, narrationHints: { energetic: 'Look down at your front foot and step the back foot forward to meet it, keeping the bind.' } },
    half_bound_lotus_tree: { name: 'Half Bound Lotus Tree', sanskrit: 'Ardha Baddha Padmottanasana', category: 'balancing', level: 'advanced', duration: { min: 15, max: 45 }, audiences: ['adults', 'advanced'], focusAreas: ['balance', 'flexibility'], bodyParts: ['hips', 'knees'], contraindications: ['knee injury'], transitions: { goodBefore: ['tree_pose'], goodAfter: ['standing_forward_fold'] }, narrationHints: { energetic: 'Place your foot in half lotus, reach the same arm behind your back to bind the big toe.' } },
    garland_pose: { name: 'Garland Pose (Yogi Squat)', sanskrit: 'Malasana', category: 'hip_opener', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'digestion'], bodyParts: ['hips', 'ankles', 'lower-back'], contraindications: ['knee injury'], transitions: { goodBefore: ['wide_legged_forward_fold'], goodAfter: ['crow_pose', 'seated_forward_fold'] }, narrationHints: { beginner: 'Drop your hips heavy between your heels. Press elbows into knees to open the chest.' } }
};
