export const EXTENDED_POSES_7 = {
    // ==================== YIN YOGA DEEP STRETCHES ====================
    deer_pose: { name: 'Deer Pose', sanskrit: 'Deer', category: 'yin', level: 'beginner', duration: { min: 120, max: 300 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['hips', 'spine'], contraindications: ['knee injury'], transitions: { goodBefore: ['butterfly_pose'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Create pinwheel legs, one internally rotated, one externally. Fold forward over the front knee and melt.' } },
    shoelace_pose: { name: 'Shoelace Pose', sanskrit: 'Shoelace', category: 'yin', level: 'intermediate', duration: { min: 120, max: 300 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['outer-thighs', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['deer_pose'] }, narrationHints: { relaxation: 'Stack knee over knee like Cow Face, but let the spine round completely over the legs. Soften effort.' } },
    saddle_pose: { name: 'Saddle Pose', sanskrit: 'Supta Virasana (Yin)', category: 'yin', level: 'advanced', duration: { min: 120, max: 300 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['quads', 'lower-back'], contraindications: ['knee injury', 'lower back injury'], transitions: { goodBefore: ['heros_pose'], goodAfter: ['childs_pose'] }, narrationHints: { relaxation: 'Lean back onto bolsters from Hero pose. Let the lower back naturally arch and quads stretch deeply.' } },
    snail_pose: { name: 'Snail Pose', sanskrit: 'Snail', category: 'yin', level: 'advanced', duration: { min: 120, max: 300 }, audiences: ['adults', 'advanced'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['spine', 'neck'], contraindications: ['neck injury', 'pregnancy'], transitions: { goodBefore: ['savasana'], goodAfter: ['fish_pose'] }, narrationHints: { relaxation: 'Roll back like Plow pose, but round the spine entirely. Let the knees drape around the ears.' } },
    caterpillar_pose: { name: 'Caterpillar Pose', sanskrit: 'Caterpillar', category: 'yin', level: 'beginner', duration: { min: 180, max: 300 }, audiences: ['adults', 'beginners'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['hamstrings', 'spine'], contraindications: ['severe back injury'], transitions: { goodBefore: ['staff_pose'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Legs straight out, fold forward, and round the back. No pulling, just allow gravity to do the work.' } },
    
    // ==================== MORE YIN & RESTORATIVE ====================
    bananasana: { name: 'Banana Pose', sanskrit: 'Bananasana', category: 'yin', level: 'beginner', duration: { min: 180, max: 300 }, audiences: ['adults', 'beginners', 'pregnant', 'seniors'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['side-body', 'obliques'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Lying on your back, curve your arms and legs to the right, making a banana shape. Breathe along the left ribs.' } },
    square_pose: { name: 'Square Pose', sanskrit: 'Square', category: 'yin', level: 'intermediate', duration: { min: 120, max: 300 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility'], bodyParts: ['hips', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['easy_pose'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { relaxation: 'Stack shins parallel to the top of the mat. Rest here, enduring the sensation with slow breathing.' } },
    sleeping_swan: { name: 'Sleeping Swan', sanskrit: 'Sleeping Swan', category: 'yin', level: 'intermediate', duration: { min: 180, max: 300 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['hips'], contraindications: ['knee injury'], transitions: { goodBefore: ['downward_facing_dog'], goodAfter: ['childs_pose'] }, narrationHints: { relaxation: 'Similar to Pigeon but entirely passive. Pad the hip with a blanket and surrender.' } },
    dragon_pose: { name: 'Dragon Pose', sanskrit: 'Dragon', category: 'yin', level: 'intermediate', duration: { min: 120, max: 300 }, audiences: ['adults', 'intermediate'], focusAreas: ['flexibility'], bodyParts: ['hip-flexors'], contraindications: ['knee injury'], transitions: { goodBefore: ['downward_facing_dog'], goodAfter: ['childs_pose'] }, narrationHints: { relaxation: 'A deep, passive lunge. Keep hands inside the foot or drop to forearms, breathing through the fire in the hip flexor.' } },
    melting_heart: { name: 'Melting Heart', sanskrit: 'Anahatasana', category: 'yin', level: 'beginner', duration: { min: 120, max: 300 }, audiences: ['adults', 'beginners'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['shoulders', 'chest', 'upper-back'], contraindications: ['shoulder injury'], transitions: { goodBefore: ['cat_cow'], goodAfter: ['childs_pose'] }, narrationHints: { relaxation: 'Hips over knees, arms stretch out, heart melts to the mat. Find stillness in the opening.' } },

    // ==================== GENTLE SOMATICS ====================
    constructive_rest: { name: 'Constructive Rest', sanskrit: 'Constructive Rest', category: 'restorative', level: 'beginner', duration: { min: 120, max: 300 }, audiences: ['adults', 'beginners', 'seniors', 'pregnant'], focusAreas: ['relaxation', 'back-pain', 'sleep'], bodyParts: ['lower-back', 'psoas'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['wind_relieving_pose'] }, narrationHints: { relaxation: 'Lie on your back, knees bent, feet wide. Knock knees together to release the psoas completely.' } },
    pentacle_pose: { name: 'Pentacle Pose', sanskrit: 'Pentacle', category: 'restorative', level: 'beginner', duration: { min: 180, max: 300 }, audiences: ['adults', 'beginners', 'kids'], focusAreas: ['relaxation', 'energy'], bodyParts: ['full-body'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['savasana'] }, narrationHints: { relaxation: 'Like Savasana, but star-fished out wide. Take up space and breathe into the edges of your body.' } },
    crocodile_pose: { name: 'Crocodile Pose', sanskrit: 'Makarasana', category: 'restorative', level: 'beginner', duration: { min: 60, max: 180 }, audiences: ['adults', 'beginners', 'kids'], focusAreas: ['relaxation', 'breathing'], bodyParts: ['lower-back', 'diaphragm'], contraindications: ['pregnancy'], transitions: { goodBefore: ['locust_pose'], goodAfter: ['childs_pose'] }, narrationHints: { relaxation: 'Lie on your belly, stack your hands, rest your forehead. Feel your belly push against the floor as you breathe in.' } },
    supported_childs_pose: { name: 'Supported Child\'s Pose', sanskrit: 'Salamba Balasana', category: 'restorative', level: 'beginner', duration: { min: 180, max: 600 }, audiences: ['adults', 'beginners', 'pregnant', 'seniors'], focusAreas: ['relaxation', 'stress-relief'], bodyParts: ['spine', 'hips'], contraindications: ['knee injury'], transitions: { goodBefore: ['cat_cow'], goodAfter: ['easy_pose'] }, narrationHints: { relaxation: 'Hug a large bolster lengthwise between your knees. Turn one cheek to the side and rest like a child.' } },
    sandbag_savasana: { name: 'Weighted Savasana', sanskrit: 'Savasana Variation', category: 'restorative', level: 'beginner', duration: { min: 300, max: 900 }, audiences: ['adults', 'beginners', 'athletes'], focusAreas: ['relaxation', 'stress-relief'], bodyParts: ['nervous-system'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['easy_pose'] }, narrationHints: { relaxation: 'Imagine heavy sandbags on your hips and shoulders, anchoring your nervous system deeply into the earth.' } },

    // ==================== MORE WALL POSES ====================
    wall_straddle: { name: 'Wall Straddle', sanskrit: 'Upavistha Konasana at Wall', category: 'restorative', level: 'beginner', duration: { min: 180, max: 300 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['inner-thighs', 'hips'], contraindications: [], transitions: { goodBefore: ['legs_up_the_wall'], goodAfter: ['legs_up_the_wall'] }, narrationHints: { relaxation: 'From legs up the wall, let the legs slide open into a wide V. Gravity gives a passive inner thigh stretch.' } },
    wall_butterfly: { name: 'Wall Butterfly', sanskrit: 'Baddha Konasana at Wall', category: 'restorative', level: 'beginner', duration: { min: 180, max: 300 }, audiences: ['adults', 'beginners', 'pregnant'], focusAreas: ['flexibility', 'relaxation'], bodyParts: ['hips', 'groin'], contraindications: [], transitions: { goodBefore: ['legs_up_the_wall'], goodAfter: ['legs_up_the_wall'] }, narrationHints: { relaxation: 'Bring soles of feet together, resting the outer edges against the wall. Let knees fall toward the wall.' } },
    wall_figure_four: { name: 'Wall Figure Four', sanskrit: 'Wall Pigeon', category: 'restorative', level: 'beginner', duration: { min: 120, max: 300 }, audiences: ['adults', 'beginners', 'seniors'], focusAreas: ['flexibility', 'back-pain'], bodyParts: ['hips', 'glutes'], contraindications: ['knee injury'], transitions: { goodBefore: ['legs_up_the_wall'], goodAfter: ['legs_up_the_wall'] }, narrationHints: { relaxation: 'Plant one foot on the wall softly, cross the other ankle over that knee to stretch the outer hip.' } },
    down_dog_on_wall: { name: 'Wall Down Dog', sanskrit: 'Wall Downward Dog', category: 'restorative', level: 'beginner', duration: { min: 30, max: 90 }, audiences: ['adults', 'beginners', 'seniors', 'office-workers'], focusAreas: ['flexibility', 'posture'], bodyParts: ['shoulders', 'spine', 'hamstrings'], contraindications: [], transitions: { goodBefore: ['mountain_pose'], goodAfter: ['mountain_pose'] }, narrationHints: { beginner: 'Stand facing the wall, press hands at hip height, walk back to form an L shape with your body.' } },
    legs_on_chair: { name: 'Legs on Chair', sanskrit: 'Chair Savasana', category: 'restorative', level: 'beginner', duration: { min: 300, max: 600 }, audiences: ['adults', 'beginners', 'seniors', 'pregnant'], focusAreas: ['relaxation', 'back-pain'], bodyParts: ['lower-back', 'legs'], contraindications: [], transitions: { goodBefore: ['savasana'], goodAfter: ['easy_pose'] }, narrationHints: { relaxation: 'Drape your calves over the seat of a chair. This relieves 100% of the pressure on your lower spine.' } }
};
